M48
; DRILL file KiCad 10.0.6 date 2026-09-28T08:13:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T08:13:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X4.6Y48.0
X11.4Y48.0
T2
X5.0Y95.0
X5.0Y5.0
X95.0Y95.0
X95.0Y5.0
M30
